/* Cronograma e conteúdo padrão. Importado pelo administrador em Configurações → "Importar cronograma padrão".
   Cada tarefa tem: id estável, data (k), frente (f), papel responsável (owner_role) e dependências (deps).

   REGRAS DESTA VERSÃO (v7):
   - Os 3 ATOS da narrativa continuam nas datas originais (Ato 1 05→14/10 · Ato 2 15→25/10 · Ato 3 26/10→06/11).
   - Os 3 LOTES do ingresso NÃO acompanham os atos:
       Lote 1 · 05/10 → 31/10   |   Lote 2 · 01/11 → 05/11 (não pode virar antes de 01/11)   |   Lote 3 · 06/11 e 07/11 apenas.
   - Duas páginas de venda do ingresso: A (sem VSL) e B (com VSL). Mesmo checkout. Teste A/B no tráfego.
   - A base de conteúdo da Paula no Instagram NÃO muda. O que muda a partir de 05/10: todo post ganha CTA para o ingresso
     ("comenta a PALAVRA que eu te mando o link") + lives chamando para o evento.
   - ManyChat: comentário/DM com a palavra-chave → DM automática com o link de compra do lote atual. */
window.PPV_SEED = (function () {
  const CONTENT_V = 7;
  const pad = n => String(n).padStart(2, "0");
  const K = (m, d) => `2026-${pad(m)}-${pad(d)}`;
  const addDays = (k, n) => { const [y, m, d] = k.split("-").map(Number); const dt = new Date(y, m - 1, d); dt.setDate(dt.getDate() + n); return `${dt.getFullYear()}-${pad(dt.getMonth() + 1)}-${pad(dt.getDate())}`; };
  const ROLE_OF = { cont: "expert", traf: "gestor_trafego", copy: "copywriter", wa: "operacao", tech: "gestor_projetos", ev: "gestor_projetos" };

  const tasks = [];
  const add = (id, k, f, t, s, r, deps, owner_role) => tasks.push({ id, k, f, t, s: s || "", r: r || "", depends_on: deps || [], owner_role: owner_role || ROLE_OF[f] });

  const CTA = "Comenta a PALAVRA-CHAVE que eu te mando o link do ingresso";

  /* ---------- PREPARAÇÃO 28/09 → 04/10 ---------- */
  add("p-nome", K(9, 28), "ev", "Bater o nome definitivo da imersão", "Provisório: Família Forte — O Começo. Validar junto à promessa e à identidade visual antes de gravar qualquer peça.", "Nome simples, humano, familiar, ligado à ideia de construção.");
  add("p-lotes", K(9, 28), "ev", "Definir preços dos 3 lotes do ingresso (datas já fixadas)", "Lote 1 = R$ 27,90 · 05/10 → 31/10. Lote 2 · 01/11 → 05/11 (NÃO vira antes de 01/11). Lote 3 · 06/11 e 07/11 apenas. Definir preço dos lotes 2 e 3 e registrar em Decisões.", "Os lotes NÃO acompanham os atos: os atos preparam a cabeça da mãe; os lotes criam urgência só na reta final.");
  add("p-palavra", K(9, 28), "ev", "Definir a palavra-chave do ManyChat", "Uma palavra curta, fácil de digitar, ligada ao evento (ex.: FAMÍLIA, COMEÇO, IMERSÃO). Registrar em Decisões. É a mesma em todos os posts, stories e lives.", "Uma palavra só, do começo ao fim: a mãe precisa decorar.");
  add("p-funil", K(9, 28), "cont", "Mapear o funil de conteúdo da Paula (topo → meio → fundo)", "A base de conteúdo é a MESMA que ela já produz no Instagram: não muda formato, tema nem frequência. O que muda a partir de 05/10: todo post termina com CTA para o ingresso (palavra-chave → ManyChat) e entram lives chamando para o evento. Registrar na aba Funil.", "Cada peça responde: em qual ato estamos e qual conclusão a mãe precisa ter.", [], "gestor_projetos");
  add("p-avatar", K(9, 28), "tech", "Preencher Raio X + Nicho, Avatar e Roma", "Avatar: mãe cristã, casada, 30–45, filhos de 2 a 10, trabalha fora. Roma DSA: 'uma família com direção'.", "");
  add("p-oferta-ing", K(9, 29), "ev", "Fechar a oferta do ingresso", "Nome, o que os 2 dias entregam, bônus de quem compra no Lote 1, garantia.", "A imersão não é 'curso de birra' nem palestra longa.", ["p-nome", "p-lotes"]);
  add("p-oferta-ff", K(9, 29), "ev", "Fechar a oferta do Família Forte 2.0", "Preço vitalício da Black Friday antecipada, entregáveis, bônus, garantia, prazo do carrinho.", "A narrativa não pode depender do desconto.");

  /* Páginas de venda: A (sem VSL) e B (com VSL) */
  add("p-copy-pagina", K(9, 29), "copy", "Copy da página A (SEM VSL) + página de obrigado", "Página de vendas direta: headline, cenas da casa, o que os 2 dias entregam, preço do lote atual + próximo lote anunciado, garantia, FAQ. Obrigado: 'você vai receber uma mensagem no WhatsApp agora'.", "Linguagem da mãe (zero técnica).", ["p-oferta-ing"]);
  add("p-copy-vsl", K(9, 30), "copy", "Roteiro da VSL da página B (COM VSL)", "Vídeo de 6–10 min: cena de reconhecimento → por que resolver separado não funciona → o que são os dois dias → oferta do lote atual → CTA. Copy da página B: headline + botão + preço abaixo do vídeo (copy curta).", "A VSL conta o mesmo filme dos atos, condensado.", ["p-oferta-ing"]);
  add("p-gravar-vsl", K(10, 1), "cont", "Gravar a VSL", "Seguindo o roteiro aprovado. Entregar editada com legenda.", "", ["p-copy-vsl"]);
  add("p-pagina", K(9, 30), "tech", "Publicar página A (sem VSL) + checkout + página de obrigado", "Montar com a copy aprovada. Sem link de grupo. URL: /ingresso", "Aqui a conversão é COMPRA, não lead.", ["p-copy-pagina"]);
  add("p-pagina-vsl", K(10, 2), "tech", "Publicar página B (com VSL) — mesmo checkout", "URL: /ingresso-v. Mesmo checkout e mesma página de obrigado da página A. Botão abaixo do vídeo.", "Duas páginas, um checkout: o teste é só na página.", ["p-gravar-vsl", "p-copy-vsl", "p-pagina"]);

  /* ManyChat (Instagram) */
  add("p-manychat-conta", K(9, 29), "wa", "Conectar o ManyChat ao Instagram da Paula", "Conta profissional, permissões de mensagens no Meta Business, número/página vinculados. Testar com comentário de teste.", "Sem a conexão aprovada, nenhum post converte.");
  add("p-copy-manychat", K(9, 30), "copy", "Copies das automações do ManyChat", "1) Resposta pública ao comentário ('te mandei no direct 💛'). 2) DM com o link do ingresso (lote atual). 3) Follow-up 24h se não clicou. 4) Follow-up 'lote vira em X dias' para quem clicou e não comprou. 5) Resposta a story/menção. 6) Versão 'vendas encerradas'.", "Curto, na linguagem da mãe, com o link em destaque.", ["p-palavra"]);
  add("p-manychat-fluxos", K(10, 2), "wa", "Montar os fluxos do ManyChat (palavra-chave → link do ingresso)", "Gatilhos: comentário com a palavra-chave em QUALQUER post, DM com a palavra-chave, resposta de story. Ação: DM com link da página (UTM manychat) + follow-ups. Tag 'clicou' e 'comprou' (via webhook do checkout).", "", ["p-manychat-conta", "p-copy-manychat", "p-pagina"]);
  add("p-manychat-teste", K(10, 3), "wa", "Testar o ManyChat de ponta a ponta", "Comentar a palavra em um post → receber DM em <1 min → link abre a página certa → compra de teste marca a tag 'comprou'.", "", ["p-manychat-fluxos"]);

  /* WhatsApp API */
  add("p-api-conta", K(9, 29), "wa", "Conta WhatsApp Business API oficial pronta", "Número dedicado, verificação Meta, nome 'Família Forte', foto e descrição. Escolher provedor (BSP).", "Sem grupos e sem Joinzap: mensagens 1:1 pela API.");
  add("p-copy-wa", K(9, 29), "copy", "Copies dos templates de aquecimento (WhatsApp)", "Boas-vindas + pesquisa, guarde a data, virada de lote, faltam 7/4/1 dias, instruções, nutrição por ato.", "");
  add("p-api-templates", K(9, 30), "wa", "Enviar templates de aquecimento para aprovação da Meta", "Cadastrar os templates aprovados pela copy.", "Aprovação leva de horas a 48h; aprovados até 03/10.", ["p-api-conta", "p-copy-wa"]);
  add("p-api-integra", K(10, 1), "wa", "Integrar checkout → disparo automático", "Webhook 'compra aprovada' dispara boas-vindas na hora. Testar com compra real e estornar.", "", ["p-pagina", "p-api-conta"]);
  add("p-pixel", K(10, 1), "tech", "Pixel + evento de compra nas páginas A e B", "Pixel Meta nas duas páginas; Purchase na página de obrigado; domínio verificado; tag do Google. UTM diferente por página (A/B) e por origem (ads, manychat, bio, stories).", "", ["p-pagina"]);
  add("p-copy-email", K(10, 1), "copy", "Sequência de e-mail pós-compra + pesquisa de avatar", "1) Obrigado + pesquisa (imediato) · 2) Salve o número da Paula (D+1) · 3) Guarde a data (D+3). Pesquisa: idade dos filhos, maior incêndio do dia, o que já tentou, o marido concorda?", "");
  add("p-email-config", K(10, 2), "tech", "Programar a sequência de e-mail no e-mail marketing", "", "", ["p-copy-email", "p-pagina"]);

  /* Criativos e tráfego */
  add("p-copy-criativos", K(9, 30), "copy", "Copies dos 10 criativos de VENDA DE INGRESSO", "Chamada para evento pago: 'dois dias para parar de resolver cada problema separado'. Base: os virais da Paula que mais performaram.", "Nada de culpabilizar a mãe ou vilanizar a criança.", ["p-oferta-ing"]);
  add("p-gravar-criativos", K(10, 1), "cont", "Gravar os vídeos dos 10 criativos de venda", "Seguindo as copies aprovadas.", "", ["p-copy-criativos"]);
  add("p-plan-trafego", K(10, 1), "traf", "Planejamento de investimento", "Meta de ingressos, CPA-alvo por lote (Lote 1 é o mais longo: 05→31/10), orçamento diário. Reservar verba para o teste A/B de páginas.", "Campanha de CONVERSÃO otimizada para Purchase.", ["p-lotes"]);
  add("p-campanhas", K(10, 2), "traf", "Montar campanhas de captação (compra) para 05/10", "Públicos: interesses do avatar, Envolvimento 60D, VV 25%/95% dos virais, Lookalike 1%, remarketing da página. 5 anúncios iniciais.", "Criar 2 dias antes: aprovação leva até 48h.", ["p-gravar-criativos", "p-pixel", "p-plan-trafego"]);
  add("p-teste-ab", K(10, 3), "traf", "Estruturar o teste A/B: página A (sem VSL) × página B (com VSL)", "Mesmos anúncios e públicos, verba dividida 50/50, conjuntos separados apontando para /ingresso e /ingresso-v. Medir CPA e conversão da página por 7 dias.", "Só a página muda. Não mexer em criativo e público durante o teste.", ["p-campanhas", "p-pagina-vsl"]);
  add("p-rmk-ingresso", K(10, 2), "traf", "Remarketing de carrinho abandonado do ingresso", "Visitou checkout e não comprou. Roda até 07/11.", "", ["p-pixel"]);
  add("p-lives-plan", K(10, 2), "cont", "Programar as lives chamando para o evento (Ato 1)", "Dias, horários e temas. Toda live tem um momento de convite explícito para a imersão + palavra-chave. Registrar em Funil → Programação de lives.", "As lives são o que entra A MAIS na rotina de conteúdo dela.", ["p-palavra"], "gestor_projetos");
  add("p-virais-plan", K(10, 2), "cont", "Planejar os posts do Ato 1 (mesma base de conteúdo da Paula)", "Manter exatamente os formatos e temas que já funcionam no Instagram dela. Só acrescentar: legenda termina com a CTA da palavra-chave; sticker/caixa na capa quando fizer sentido.", "Não inventar conteúdo novo: a base é a dela.", ["p-funil", "p-palavra"], "gestor_projetos");
  add("p-bio", K(10, 4), "wa", "Atualizar bio, destaque e link do Instagram", "Bio com a data e a palavra-chave; destaque 'Imersão'; link da bio → página A (UTM bio).", "", ["p-pagina"]);
  add("p-teste", K(10, 4), "tech", "Checklist final de virada", "Teste ponta a ponta: anúncio → página A e página B → checkout → obrigado → WhatsApp em <1 min → e-mail. Comentário com a palavra → DM do ManyChat → página.", "Se qualquer elo falhar, a captação NÃO abre dia 05/10.", ["p-api-integra", "p-email-config", "p-campanhas", "p-pagina-vsl", "p-manychat-teste"]);

  /* ---------- ROTINAS SEMANAIS ---------- */
  const weeks = [[K(10, 5), "ato1"], [K(10, 12), "ato2"], [K(10, 19), "ato2"], [K(10, 26), "ato3"], [K(11, 2), "ato3"]];
  const ACT = { ato1: "Ato 1 · reconhecimento: dar nome ao que a mãe vive. Não entregar a solução completa.", ato2: "Ato 2 · mudar a interpretação: amor e limite não são opostos; autoridade ≠ grito; info solta ≠ direção.", ato3: "Ato 3 · possibilidade: histórias reais, antes/depois, demonstrações. 'Isso cabe na minha vida.'" };
  const LIVE = { ato1: "Cena real da casa: tablet, ordem repetida, culpa, casal discorda, apagar incêndio. Convite para a imersão + palavra-chave.", ato2: "Padrões: 'não é falta de amor'; por que dica solta não vira rotina. Convite para a imersão + palavra-chave.", ato3: "Prova e demonstração prática; convite direto para a imersão + palavra-chave (e o lote que está aberto)." };
  const LOTE_W = { w1: "Lote 1 (R$ 27,90)", w2: "Lote 1 (R$ 27,90)", w3: "Lote 1 (R$ 27,90)", w4: "Lote 1 até 31/10 → vira Lote 2 em 01/11", w5: "Lote 2 até 05/11 → Lote 3 em 06 e 07/11" };
  weeks.forEach(([mon, ph], i) => {
    const w = "w" + (i + 1), prevFri = addDays(mon, -3);
    const mix = mon === "2026-10-12" ? " (segunda a quarta ainda Ato 1; virada para o Ato 2 na quinta 15/10)" : "";
    add(`${w}-copy`, prevFri, "copy", `Semana ${i + 1}: legendas com CTA, roteiros das lives, e-mail e WhatsApp`, ACT[ph] + mix + ` Legendas dos posts da semana (mesma base de conteúdo) terminando com a CTA da palavra-chave. Lote da semana: ${LOTE_W[w]}.`, "A copy da semana precisa estar pronta na sexta anterior — sem ela a expert não grava e o tráfego não distribui.", i === 0 ? ["p-virais-plan"] : [`w${i}-copy`]);
    add(`${w}-virais`, mon, "cont", `Semana ${i + 1}: publicar os posts da semana (mesma base) com CTA para o ingresso`, `Os mesmos formatos e temas que ela já faz. Toda legenda termina com: "${CTA}". Fixar um comentário da própria Paula com a palavra.`, "A base não muda; a CTA entra em TODOS os posts a partir de 05/10.", [`${w}-copy`]);
    add(`${w}-cortes`, mon, "cont", `Semana ${i + 1}: cortes das lives e stories chamando para o evento`, "Cortes da live anterior + stories diários com caixinha/sticker da palavra-chave; link direto nos stories.", "Meio: aprofundar consciência.", i === 0 ? [] : [`w${i}-live2`]);
    if (i > 0) add(`${w}-distrib`, mon, "traf", `Semana ${i + 1}: distribuição paga do conteúdo da semana anterior`, "Campanha de visualização com os posts e cortes da semana passada. Duplicar, trocar vídeos, ajustar data.", "", [`w${i}-virais`]);
    add(`${w}-orc`, mon, "traf", `Semana ${i + 1}: otimizar orçamento da captação (seg a qui)`, "Novo orçamento diário = compras de ontem × CPA ideal. Registrar no Planilhamento.", "");
    add(`${w}-criat`, addDays(mon, 2), "traf", `Semana ${i + 1}: otimizar criativos (segunda e quarta)`, "Pausar anúncios com CPA acima do alvo; subir novos.", "");
    add(`${w}-pub`, addDays(mon, 3), "traf", `Semana ${i + 1}: otimizar públicos (quinta)`, "Pausar públicos acima do CPA-alvo; adicionar novos.", "");
    add(`${w}-live1`, addDays(mon, 1), "cont", `Semana ${i + 1}: Live 1 chamando para o evento (ver Programação de lives)`, LIVE[ph], "Mín. 30 min. Convite explícito + palavra-chave no meio e no fim. Postar o link como evidência.", [`${w}-copy`]);
    add(`${w}-live2`, addDays(mon, 3), "cont", `Semana ${i + 1}: Live 2 chamando para o evento (ver Programação de lives)`, "", "Mín. 30 min. Convite explícito + palavra-chave.", [`${w}-copy`]);
    add(`${w}-manychat`, mon, "wa", `Semana ${i + 1}: conferir o ManyChat (link do lote atual, respostas, taxa de clique)`, `Link e preço do lote da semana (${LOTE_W[w]}) corretos na DM; responder DMs que saíram do fluxo; anotar comentários→DM→cliques→compras.`, "Se o link estiver com o lote errado, toda a CTA da semana vende errado.", [`${w}-virais`]);
    add(`${w}-wa`, addDays(mon, 1), "wa", `Semana ${i + 1}: mensagem de nutrição para compradoras (API)`, "Template aprovado. Uma cena + uma pergunta + lembrete leve da data.", "WhatsApp aproxima, lembra e conduz.", [`${w}-copy`]);
    add(`${w}-email`, addDays(mon, 3), "tech", `Semana ${i + 1}: disparar o e-mail da narrativa`, "Segmentar compradoras × não compradoras (convite + lote atual).", "", [`${w}-copy`]);
    add(`${w}-reuniao`, addDays(mon, 4), "ev", `Semana ${i + 1}: reunião de ato — coerência dos canais e vendas × meta`, "Instagram, lives, e-mail e WhatsApp contam o MESMO filme? Vendas por origem (ads A/B, ManyChat, bio, stories). Ajustes para a próxima semana.", "Se a peça não responde 'qual conclusão a mãe precisa ter', ela não entra.");
  });

  /* ---------- MARCOS ---------- */
  add("m-captacao", K(10, 5), "traf", "Ativar captação (venda de ingresso) — Lote 1 (05/10 → 31/10)", "Campanhas ativas nas duas páginas (teste A/B), pixel disparando Purchase, orçamento conforme planejamento.", "CAPTAÇÃO COMEÇA HOJE.", ["p-teste"]);
  add("m-cta-on", K(10, 5), "cont", "A partir de hoje: todo post com CTA para o ingresso", "Nenhum post sai sem a palavra-chave na legenda. Comentário fixado da Paula com a palavra.", "Regra permanente até 07/11.", ["p-manychat-teste"]);
  add("m-api-ok", K(10, 5), "wa", "Confirmar templates aprovados e disparo automático funcionando", "Primeira compra do dia = primeira boas-vindas.", "", ["p-api-templates", "p-api-integra"]);
  add("m-ab-decisao", K(10, 12), "traf", "Decidir a página vencedora do teste A/B (VSL × sem VSL)", "Comparar CPA e conversão de 05→11/10. Concentrar 70–80% da verba na vencedora; manter a outra viva para remarketing. Registrar em Decisões.", "Decisão por número, não por gosto.", ["p-teste-ab"]);
  add("m-provas", K(10, 12), "ev", "Coletar provas sociais para o Ato 3", "Depoimentos de alunas do FF 1.0, prints, antes/depois de rotina. Pedir autorização.", "");
  add("m-copy-ato2", K(10, 13), "copy", "Copies dos criativos do Ato 2", "Mensagem de quebra de crença. Preço continua o do Lote 1 (R$ 27,90) — a urgência ainda não é de lote, é de conclusão.", "");
  add("m-gravar-ato2", K(10, 14), "cont", "Gravar criativos do Ato 2", "", "", ["m-copy-ato2"]);
  add("m-trocar-ato2", K(10, 15), "traf", "Trocar criativos para o Ato 2 (Lote 1 continua)", "5 novos anúncios. Preço e páginas não mudam.", "", ["m-gravar-ato2"]);
  add("m-roteiro-d1", K(10, 19), "copy", "Roteiro da Imersão — Dia 1", "Reconhecer → entender → descobrir. Arquétipo Jeito Errado / Jeito Certo.", "", ["p-oferta-ff"]);
  add("m-roteiro-d2", K(10, 20), "copy", "Roteiro da Imersão — Dia 2", "Aplicar → método e continuidade → oferta do FF 2.0 como consequência lógica.", "", ["m-roteiro-d1"]);
  add("m-pitch", K(10, 21), "copy", "Roteiro da oferta (pitch) do FF 2.0", "Transformação, entregáveis, bônus, garantia, condição vitalícia, prazo. Desmontar as 7 objeções antes do preço.", "", ["m-roteiro-d2"]);
  add("m-roteiro-ok", K(10, 22), "cont", "Expert valida os roteiros dos dois dias e do pitch", "Ajustes finais com a Paula.", "", ["m-pitch"]);
  add("m-emails-lanc", K(10, 22), "copy", "E-mails de lançamento do FF 2.0 (8 peças)", "Inscrições abertas (3 no dia 1), Estamos vivos, Atendendo a pedidos, Encerramento, Encerram hoje, Últimas horas.", "", ["m-pitch"]);
  add("m-copy-evento-wa", K(10, 22), "copy", "Copies dos templates de EVENTO e OFERTA (WhatsApp)", "Começa em 1h · ao vivo · replay · oferta aberta · vagas/bônus · encerra hoje · últimas horas · boleto · recusada.", "", ["m-pitch"]);
  add("m-templates-evento", K(10, 23), "wa", "Enviar templates de EVENTO e OFERTA para aprovação", "", "Aprovados até 30/10.", ["m-copy-evento-wa"]);
  add("m-copy-ato3", K(10, 22), "copy", "Copies dos criativos do Ato 3", "Provas, depoimentos, 'faltam 12 dias'. Versões com 'Lote 1 acaba 31/10'.", "", ["m-provas"]);
  add("m-gravar-ato3", K(10, 23), "cont", "Gravar criativos do Ato 3", "", "", ["m-copy-ato3"]);
  add("m-trocar-ato3", K(10, 26), "traf", "Trocar criativos para o Ato 3 (Lote 1 até 31/10)", "", "", ["m-gravar-ato3"]);
  add("m-copy-ff", K(10, 26), "copy", "Copy da página de vendas do Família Forte 2.0", "Oferta vitalícia.", "", ["m-pitch"]);
  add("m-pagina-ff", K(10, 27), "tech", "Página de vendas + checkout do Família Forte 2.0", "Página escondida até 08/11. Evento Purchase separado.", "", ["m-copy-ff"]);
  add("m-copy-recup", K(10, 27), "copy", "Copies de recuperação de vendas (e-mail e WhatsApp)", "Carrinho abandonado #1/#2, compra cancelada, boleto #1/#2.", "");
  add("m-copy-lotes", K(10, 27), "copy", "Copies das viradas de lote (WhatsApp, e-mail, stories, ManyChat)", "'Faltam 3 dias para o Lote 1 acabar' (29/10) · 'Último dia do Lote 1' (31/10) · 'Lote 2 aberto' (01/11) · 'Lote 2 acaba em 3 dias' (03/11) · 'Último dia do Lote 2' (05/11) · 'Lote 3: só hoje e amanhã' (06/11) · 'Última chamada: encerra hoje' (07/11).", "Escassez real: as datas não mudam.", ["p-lotes"]);
  add("m-recup-config", K(10, 28), "tech", "Programar automações de recuperação de vendas", "", "", ["m-copy-recup", "m-pagina-ff"]);
  add("m-copy-rmk", K(10, 28), "copy", "Copies de remarketing (7 lembrete · 4 ao vivo · 7 carrinho aberto)", "", "");

  /* Virada Lote 1 → 2 */
  add("m-lote2-aviso", K(10, 29), "wa", "Comunicar: Lote 1 acaba em 3 dias (WhatsApp, e-mail, stories, ManyChat)", "Não compradoras com contato + quem clicou no ManyChat e não comprou.", "", ["m-copy-lotes"]);
  add("m-gravar-rmk", K(10, 29), "cont", "Gravar criativos de remarketing", "", "", ["m-copy-rmk"]);
  add("m-templates-ok", K(10, 30), "wa", "Confirmar aprovação de todos os templates do evento", "Ter mensagem alternativa pronta.", "", ["m-templates-evento"]);
  add("m-rmk-lembrete", K(10, 30), "traf", "Montar remarketing 'Faltam X dias' e 'Estamos ao vivo'", "Alcance para compradoras + tráfego para não compradoras (última chamada).", "", ["m-gravar-rmk"]);
  add("m-lote1-fim", K(10, 31), "wa", "Último dia do Lote 1 — 'últimas horas' (WhatsApp, stories, ManyChat)", "Disparo + story de contagem + DM do ManyChat para quem clicou e não comprou.", "", ["m-copy-lotes"]);
  add("m-e7", K(10, 31), "tech", "E-mail 'Faltam 7 dias' + 'Último dia do Lote 1'", "Compradoras: agenda. Não compradoras: hoje é o último dia a R$ 27,90.", "", ["m-copy-lotes"]);
  add("m-w7", K(10, 31), "wa", "WhatsApp 'Faltam 7 dias' (compradoras)", "", "");
  add("m-lote2-checkout", K(11, 1), "tech", "Virar para o Lote 2 (00h de 01/11): checkout + páginas A e B", "Atualizar preço no checkout e nas DUAS páginas. Testar compra. Não virar antes de 01/11.", "Lote 2 abre exatamente em 01/11.", ["p-lotes"]);
  add("m-lote2-manychat", K(11, 1), "wa", "Atualizar o ManyChat para o Lote 2 (link/preço na DM) + aviso 'Lote 2 aberto'", "Trocar o texto de preço na DM; disparar para quem clicou e não comprou.", "", ["m-lote2-checkout"]);
  add("m-lote2-ads", K(11, 1), "traf", "Atualizar anúncios para o preço do Lote 2", "Trocar textos/preço nos criativos ativos e no remarketing de carrinho.", "", ["m-lote2-checkout"]);
  add("m-plataforma", K(11, 2), "ev", "Definir plataforma e fluxo de acesso do evento", "Onde a mãe assiste, link único por compradora?, replay, suporte ao vivo.", "");

  /* Virada Lote 2 → 3 */
  add("m-lote3-aviso", K(11, 3), "wa", "Comunicar: Lote 2 acaba em 3 dias (WhatsApp, e-mail, stories, ManyChat)", "", "", ["m-copy-lotes"]);
  add("m-e4", K(11, 3), "tech", "E-mail 'Faltam 4 dias' + 'Lote 2 acaba em 3 dias'", "Compradoras: o que vai sair sabendo. Não compradoras: Lote 2 até 05/11.", "", ["m-copy-lotes"]);
  add("m-w4", K(11, 3), "wa", "WhatsApp 'Faltam 4 dias' (compradoras)", "", "");
  add("m-rmk-ff", K(11, 4), "traf", "Montar remarketing de carrinho do FF 2.0 (para 08/11)", "Viu a imersão, visitou página de vendas, compradoras do ingresso, lista total.", "", ["m-gravar-rmk", "m-pagina-ff"]);
  add("m-lote2-fim", K(11, 5), "wa", "Último dia do Lote 2 — 'últimas horas' (WhatsApp, e-mail, stories, ManyChat)", "", "", ["m-copy-lotes"]);
  add("m-ensaio", K(11, 5), "ev", "Ensaio técnico da transmissão", "Áudio, luz, slides, link, chat, plano B. Simular a virada para a oferta.", "", ["m-plataforma", "m-roteiro-ok"]);
  add("m-guerra", K(11, 5), "ev", "Reunião de guerra: papéis dos 2 dias", "Quem apresenta, modera chat, responde WhatsApp e ManyChat, monitora checkout, posta stories.", "");
  add("m-lote3-checkout", K(11, 6), "tech", "Virar para o Lote 3 (00h de 06/11): checkout + páginas A e B", "Lote 3 vale só 06 e 07/11. Atualizar preço nas duas páginas e no checkout. Testar compra.", "", ["p-lotes"]);
  add("m-lote3-manychat", K(11, 6), "wa", "Atualizar o ManyChat para o Lote 3 + aviso 'só hoje e amanhã'", "", "", ["m-lote3-checkout"]);
  add("m-lote3-ads", K(11, 6), "traf", "Atualizar anúncios para o Lote 3 (último lote: 06 e 07/11)", "Última chamada em todos os criativos ativos.", "", ["m-lote3-checkout"]);
  add("m-e1", K(11, 6), "tech", "E-mail 'É amanhã' + instruções de acesso (compradoras) · 'Lote 3: só hoje e amanhã' (não compradoras)", "", "", ["m-plataforma", "m-copy-lotes"]);
  add("m-w1", K(11, 6), "wa", "WhatsApp 'É amanhã' + instruções", "Duas chamadas: manhã e noite.", "", ["m-plataforma", "m-templates-ok"]);

  /* ---------- IMERSÃO ---------- */
  add("e1-w1h", K(11, 7), "wa", "WhatsApp 'Começa em 1h'", "", "");
  add("e1-dia1", K(11, 7), "cont", "IMERSÃO — Dia 1 ao vivo", "Reconhecer → entender → descobrir. Gancho para o Dia 2.", "Não é palestra longa.", ["m-ensaio"]);
  add("e1-wlive", K(11, 7), "wa", "WhatsApp 'Estamos ao vivo' + 'Replay do Dia 1'", "", "");
  add("e1-email", K(11, 7), "tech", "E-mail 'Como foi o Dia 1 + amanhã tem mais' · 'Última chamada: ingresso encerra hoje'", "", "", ["m-copy-lotes"]);
  add("e1-rmk", K(11, 7), "traf", "Remarketing 'Estamos ao vivo' ativo", "", "", ["m-rmk-lembrete"]);
  add("m-ultima", K(11, 7), "traf", "Última chamada de ingresso — encerra hoje (Lote 3)", "Stories, ManyChat e anúncios: 'quem entra hoje recebe o replay do Dia 1 e assiste o Dia 2 ao vivo'. Pausar captação à meia-noite. Manter lembrete ativo.", "", ["m-lote3-ads"]);
  add("m-fechar-ing", K(11, 7), "tech", "Fechar vendas do ingresso à meia-noite e travar checkout", "Trocar páginas A e B por 'vendas encerradas'. ManyChat passa a responder 'vendas encerradas + lista de espera'.", "", ["m-lote3-checkout"]);
  add("e2-w1h", K(11, 8), "wa", "WhatsApp 'Começa em 1h' (Dia 2)", "", "");
  add("e2-dia2", K(11, 8), "cont", "IMERSÃO — Dia 2 ao vivo + abertura da oferta", "Aplicar → método → Família Forte 2.0 vitalício abre AO VIVO.", "Bônus de quem decide ao vivo.", ["e1-dia1"]);
  add("e2-checkout", K(11, 8), "tech", "Publicar página de vendas + liberar checkout do FF 2.0 no pitch", "", "", ["m-pagina-ff"]);
  add("e2-woferta", K(11, 8), "wa", "WhatsApp 'Oferta aberta' (2 chamadas) + 'Vagas com bônus e garantia'", "", "", ["e2-checkout"]);
  add("e2-emails", K(11, 8), "tech", "E-mails Dia 1 do carrinho: Inscrições abertas · Cuidado, pode perder sua vaga · Últimas horas do bônus", "", "", ["m-emails-lanc", "e2-checkout"]);
  add("e2-rmk", K(11, 8), "traf", "Ativar remarketing de carrinho do FF 2.0", "", "", ["m-rmk-ff", "e2-checkout"]);
  [[9, "Estamos vivos… (Dia 2 #1)"], [10, "Atendendo a pedidos (Dia 3 #1)"], [11, "Encerramento das inscrições (Dia 4 #1)"], [12, "As matrículas encerram hoje (#1) + Últimas horas (#2)"]].forEach(([d, t]) => {
    add(`c${d}-email`, K(11, d), "tech", "E-mail: " + t, "", "", ["m-emails-lanc"]);
    add(`c${d}-wa`, K(11, d), "wa", "WhatsApp: " + t, "", "", ["m-templates-ok"]);
    add(`c${d}-rmk`, K(11, d), "traf", "Otimizar remarketing de carrinho (diário)", "Priorizar os públicos mais quentes (assistiu o Dia 2).", "");
    add(`c${d}-recup`, K(11, d), "wa", "Recuperação manual: boleto emitido + compra recusada", "Preencher Planilha de Recuperação com status.", "", ["m-recup-config"]);
    add(`c${d}-vendas`, K(11, d), "ev", "Monitorar vendas × meta e responder objeções", "", "");
  });
  add("c9-virais", K(11, 9), "cont", "Posts e cortes com os melhores momentos da imersão", "Mesma base de conteúdo; CTA agora para o FF 2.0.", "");
  add("c12-fechar", K(11, 12), "tech", "Fechar carrinho à meia-noite", "Trocar página por lista de espera.", "");
  add("f-debrief", K(11, 13), "ev", "Debriefão do lançamento", "Números por lote (1: 05→31/10 · 2: 01→05/11 · 3: 06→07/11), CPA, página A × B, ManyChat (comentários→DM→cliques→compras), conversão ingresso→FF 2.0.", "");
  add("f-api", K(11, 13), "wa", "Exportar histórico da API e do ManyChat; manter base segmentada", "Compradoras × alunas FF 2.0 × não compradoras.", "");
  add("f-traf", K(11, 13), "traf", "Pausar campanhas e arquivar relatórios", "", "");

  tasks.forEach(t => { if (t.k < "2026-09-28") t.k = "2026-09-28"; });

  /* ---------- LIVES ---------- */
  const PH = [["ato1", "2026-10-05", "2026-10-14"], ["ato2", "2026-10-15", "2026-10-25"], ["ato3", "2026-10-26", "2026-11-06"]];
  const temas = { ato1: ["Você tira o tablet e seu filho vira outra criança?", "Quantas vezes você precisa pedir a mesma coisa?", "Você promete mais paciência e termina o dia culpada?", "Seu marido corrige de um jeito e você de outro?"], ato2: ["Nem todo comportamento é 'fase'", "Amor e limite não são opostos", "Autoridade não é grito; rotina não é quartel", "Resolver a birra sem olhar o todo só desloca o problema"], ato3: ["Caso real: a rotina que mudou em 3 semanas", "Antes e depois: a casa no modo sobrevivência", "Demonstração: o que muda em dois dias", "Última live: o que você vai sair sabendo na imersão"] };
  const loteEm = d => d <= "2026-10-31" ? "Lote 1 (R$ 27,90)" : d <= "2026-11-05" ? "Lote 2" : "Lote 3";
  const lives = []; const used = { ato1: 0, ato2: 0, ato3: 0 };
  weeks.forEach(([mon]) => [1, 3].forEach(off => { const d = addDays(mon, off); const ph = (PH.find(p => d >= p[1] && d <= p[2]) || [])[0]; if (!temas[ph]) return; lives.push({ d, h: "20h", tema: temas[ph][used[ph]++ % 4], ato: ph, cta: `Convite para a imersão + palavra-chave · ${loteEm(d)}` }); }));

  const content = {
    v: CONTENT_V,
    marks: { [K(9, 28)]: "Início da preparação", [K(10, 5)]: "Abre a narrativa · Lote 1 (R$ 27,90) · captação começa · todo post com CTA", [K(10, 12)]: "Decisão do teste A/B (VSL × sem VSL)", [K(10, 15)]: "Virada para o Ato 2 (Lote 1 continua)", [K(10, 26)]: "Virada para o Ato 3 (Lote 1 continua)", [K(10, 29)]: "Aviso: Lote 1 acaba em 3 dias", [K(10, 31)]: "Último dia do Lote 1 · Faltam 7 dias", [K(11, 1)]: "Vira o Lote 2", [K(11, 3)]: "Faltam 4 dias · Lote 2 acaba em 3 dias", [K(11, 5)]: "Último dia do Lote 2", [K(11, 6)]: "Vira o Lote 3 (só 06 e 07/11) · É amanhã", [K(11, 7)]: "IMERSÃO — Dia 1 · ingresso encerra hoje", [K(11, 8)]: "IMERSÃO — Dia 2 · oferta FF 2.0 abre ao vivo", [K(11, 12)]: "Carrinho FF 2.0 fecha (proposta)", [K(11, 13)]: "Fechamento e debrief" },
    lives,
    funil: {
      topo: [["Posts do Instagram (mesma base de conteúdo da Paula)", "Os mesmos formatos e temas que ela já produz. A partir de 05/10, toda legenda termina com a CTA da palavra-chave → ManyChat → link do ingresso", "Descoberta e identificação · transformar audiência em compradora sem mudar o conteúdo", "Alcance, comentários com a palavra, DMs enviadas, cliques"], ["Distribuição paga dos posts", "Campanha de visualização toda segunda com os posts e cortes da semana anterior", "Aquecer público frio barato", "CPV, % de retenção"], ["Criativos de venda do ingresso (público frio)", "Virais que mais performaram + CTA 'dois dias' → página A ou B", "Primeira compra (Lote 1: R$ 27,90)", "CPA por lote · CPA por página (A/B)"]],
      meio: [["Lives chamando para o evento (2 por semana)", "O que entra A MAIS na rotina dela: aprofundam consciência e convidam explicitamente para a imersão com a palavra-chave", "Levar de 'reconheço' para 'talvez eu esteja resolvendo errado' e para o clique", "Espectadores, tempo médio, comentários com a palavra"], ["Cortes das lives + stories diários", "Meio de funil orgânico com sticker/caixinha da palavra-chave e link direto", "Nutrir quem viu o post e não comprou", "Cliques no link, DMs"], ["ManyChat (Instagram)", "Comentário ou DM com a palavra-chave → DM automática com o link do lote atual → follow-ups", "Converter engajamento em visita à página sem depender do link da bio", "Comentários→DM→cliques→compras"], ["E-mail semanal + WhatsApp (API)", "E-mail argumenta; WhatsApp aproxima e lembra", "Manter a compradora aquecida e converter a não compradora", "Abertura, resposta, compras por disparo"], ["Remarketing de carrinho do ingresso", "Visitou checkout e não comprou", "Recuperar compra", "CPA do remarketing"]],
      fundo: [["Páginas de venda A (sem VSL) e B (com VSL) + 3 lotes", "Mesmo checkout. Lote 1 05→31/10 · Lote 2 01→05/11 · Lote 3 06 e 07/11", "Compra do ingresso", "Conversão por página, compras/dia, compras por lote"], ["Provas sociais (Ato 3)", "Depoimentos, antes/depois, casos reais", "'Isso cabe na minha vida'", "Compras na reta final (Lotes 2 e 3)"], ["Imersão 07 e 08/11", "Organiza tudo; Dia 2 abre a oferta ao vivo", "Decisão: 'preciso aprender a conduzir agora'", "Comparecimento, permanência no pitch"], ["Oferta FF 2.0 + remarketing + recuperação", "Vitalício, BF antecipada, bônus ao vivo, carrinho 08→12/11", "Venda do Família Forte 2.0", "Conversão ingresso→FF 2.0, faturamento"]]
    },
    manychat: [["Gatilho", "Comentário com a palavra-chave em QUALQUER post · DM com a palavra · resposta de story/menção"], ["Resposta pública", "Comentário automático curto ('te mandei no direct 💛') para puxar mais comentários"], ["DM 1 (imediata)", "Link da página do ingresso (lote atual, UTM manychat) + uma frase da promessa"], ["DM 2 (24h, não clicou)", "Lembrete leve: 'ficou com o link aí?'"], ["DM 3 (clicou e não comprou)", "Virada de lote / últimas horas conforme a data"], ["Tags", "clicou · comprou (webhook do checkout) — parar follow-ups na compra"], ["Manutenção", "Toda segunda: conferir link e preço do lote da semana; 01/11 e 06/11 trocar para o lote novo; 08/11 trocar para 'vendas encerradas + lista de espera'"], ["Regra dos posts", "A base de conteúdo NÃO muda. Toda legenda termina com: 'Comenta a PALAVRA-CHAVE que eu te mando o link do ingresso'. Comentário da Paula fixado com a palavra."]],
    paginas: [["Página A — sem VSL (/ingresso)", "Copy direta: headline, cenas da casa, o que os 2 dias entregam, preço do lote atual + próximo lote, garantia, FAQ. Link da bio e do ManyChat apontam para ela até a decisão do teste."], ["Página B — com VSL (/ingresso-v)", "VSL de 6–10 min acima da dobra, botão e preço abaixo do vídeo, copy curta."], ["Um checkout só", "As duas páginas usam o mesmo checkout e a mesma página de obrigado. Pixel e UTM separados por página."], ["Teste A/B (05→11/10)", "Tráfego dividido 50/50, mesmos anúncios e públicos. Em 12/10 concentrar verba na vencedora; a outra continua viva. Registrar em Decisões."], ["Viradas de lote", "01/11 e 06/11: atualizar preço nas DUAS páginas + checkout + ManyChat + anúncios. 08/11: as duas viram 'vendas encerradas'."]],
    wa: [["Compra aprovada", "imediato", "Boas-vindas + pesquisa", "Convite para a data + link da pesquisa. Pede para salvar o contato.", "utility"], ["Compra +1 dia", "D+1 · 9h", "Guarde a data", "Agenda dos dois dias e o que preparar.", "utility"], ["Terças (semanal, a partir de 06/10)", "9h", "Nutrição do ato", "Uma cena + uma pergunta. Um template por ato.", "marketing"], ["29/10", "10h", "Lote 1 acaba em 3 dias (não compradoras com contato)", "'Até sábado o ingresso está em R$ 27,90.'", "marketing"], ["31/10", "10h", "Faltam 7 dias (compradoras) · Último dia do Lote 1 (não compradoras)", "Agenda + convite para chamar o marido · últimas horas a R$ 27,90.", "marketing"], ["01/11", "10h", "Lote 2 aberto (não compradoras)", "Novo preço + até 05/11.", "marketing"], ["03/11", "10h", "Faltam 4 dias (compradoras) · Lote 2 acaba em 3 dias (não compradoras)", "O que a mãe vai sair sabendo.", "marketing"], ["05/11", "10h", "Último dia do Lote 2", "", "marketing"], ["06/11", "9h e 19h", "É amanhã + instruções (compradoras) · Lote 3: só hoje e amanhã (não compradoras)", "Link, horário, acesso, suporte.", "utility"], ["07/11", "1h antes", "Começa em 1h", "", "utility"], ["07/11", "na abertura", "Estamos ao vivo", "Link direto.", "utility"], ["07/11", "15h", "Última chamada: ingresso encerra hoje (não compradoras)", "Quem entra hoje recebe o replay do Dia 1.", "marketing"], ["07/11", "noite", "Replay do Dia 1 + gancho do Dia 2", "", "utility"], ["08/11", "1h antes · abertura", "Começa em 1h · Estamos ao vivo", "", "utility"], ["08/11", "no pitch · +3h", "Oferta aberta (chamada 1 e 2)", "Condição vitalícia + bônus de quem decide ao vivo.", "marketing"], ["08/11", "noite", "Vagas com bônus e garantia", "", "marketing"], ["09/11", "10h", "Estamos vivos…", "Respostas às dúvidas do chat.", "marketing"], ["10/11", "10h", "Atendendo a pedidos", "", "marketing"], ["11/11", "10h", "Encerramento das inscrições", "", "marketing"], ["12/11", "9h · 18h · 22h", "As matrículas encerram hoje · Últimas horas", "", "marketing"], ["09→12/11", "manual, diário", "Recuperação: boleto emitido · compra recusada", "1:1 pela API, script da pasta 7.", "utility"]],
    waRules: [["Templates enviados até 30/09 (aquecimento) e 23/10 (evento e oferta); aprovação pode levar 48h.", "Guardar um template alternativo genérico para emergências."], ["Janela de 24h: quando a mãe responde, a equipe conversa livremente por 24h sem template.", "Aproveitar respostas à pesquisa para relacionamento 1:1."], ["Nunca mais de 1 mensagem de marketing por dia por contato, exceto Dia 1 do carrinho e último dia.", "Número bloqueado = régua inteira parada."], ["Segmentar sempre: compradoras × não compradoras com contato × alunas FF 2.0 (parar a régua de venda na compra).", ""], ["ManyChat é Instagram (DM), WhatsApp é API: não misturar. O ManyChat entrega o link; o WhatsApp acompanha quem comprou.", ""]],
    em: [["Compra aprovada", "Obrigado + pesquisa de avatar", "Sequência automática · passo 1"], ["D+1", "Salve o número da Paula no WhatsApp", "Sequência automática · passo 2"], ["D+3", "Guarde a data: 07 e 08/11", "Sequência automática · passo 3"], ["Quintas", "E-mail da narrativa (Ato 1 / 2 / 3)", "Segmentar compradoras × não compradoras"], ["29/10", "Lote 1 acaba em 3 dias", "Não compradoras"], ["31/10", "Faltam 7 dias · Último dia do Lote 1", "Compradoras · não compradoras"], ["01/11", "Lote 2 aberto", "Não compradoras"], ["03/11", "Faltam 4 dias · Lote 2 acaba em 3 dias", "Compradoras · não compradoras"], ["05/11", "Último dia do Lote 2", "Não compradoras"], ["06/11", "É amanhã + instruções de acesso · Lote 3: só hoje e amanhã", "Compradoras · não compradoras"], ["07/11", "Como foi o Dia 1 + amanhã tem mais · Última chamada: encerra hoje", "Replay · não compradoras"], ["08/11", "Inscrições abertas · Cuidado, pode perder sua vaga · Últimas horas do bônus ao vivo", "Dia 1 do carrinho — 3 e-mails"], ["09/11", "Estamos vivos…", "Dia 2 #1"], ["10/11", "Atendendo a pedidos", "Dia 3 #1"], ["11/11", "Encerramento das inscrições", "Dia 4 #1"], ["12/11", "As matrículas encerram hoje · Últimas horas", "Dia 5 #1 e #2"], ["Automação", "Carrinho abandonado #1 e #2 · Compra cancelada · Boleto #1 e #2", "Recuperação — ingresso e FF 2.0"]],
    trafCards: [["1 · Captação (venda de ingresso)", "Campanha de conversão → Purchase. 5 anúncios iniciais por ato. Públicos: interesses do avatar, Envolvimento 60D, VV 25%/95% dos virais, Lookalike 1%, remarketing da página. Conjuntos separados para página A e página B.", "05/10 → 07/11 · trocar criativos a cada ato · preço muda 01/11 e 06/11"], ["2 · Teste A/B de páginas", "Página A (sem VSL) × página B (com VSL), 50/50, mesmos anúncios e públicos. Decisão em 12/10 por CPA; concentrar verba na vencedora.", "05/10 → 11/10 · decisão 12/10"], ["3 · Distribuição de conteúdo", "Toda segunda: visualização de vídeo com os posts e cortes da semana anterior (Meta e YouTube).", "12/10 → 09/11"], ["4 · Remarketing de carrinho do ingresso", "Visitou checkout e não comprou. Preço do lote atual + data da próxima virada como escassez.", "05/10 → 07/11 · sempre ligado"], ["5 · Lembrete (compradoras)", "Alcance para compradoras: 'Faltam X dias' e 'Estamos ao vivo'.", "31/10 → 08/11"], ["6 · Remarketing de carrinho FF 2.0", "Tráfego; conjuntos: assistiu o Dia 2, visitou página, compradoras do ingresso, lista total.", "08/11 → 12/11 · criar até 04/11"], ["7 · Criativos", "10 de venda (Ato 1) + 5 por ato · versões de preço para Lote 2 (01/11) e Lote 3 (06/11) · 7 lembrete · 4 ao vivo · 7 carrinho aberto.", "Nunca: culpa da mãe, criança vilã, medo extremo"]],
    trafMeta: ["Todo dia · orçamento: compras de ontem × CPA ideal = novo orçamento diário.", "Segunda e quarta · criativos: pausar acima do CPA-alvo, subir novos.", "Quinta · públicos: pausar acima do CPA-alvo, adicionar novos.", "Todo dia · planilhamento de vendas e criativos, separado por página (A/B) e por origem (ads, ManyChat, bio, stories)."],
    trafGoogle: ["Todo dia · orçamento (se gastou tudo dentro do CPA, aumenta) e lance de CPA por grupo.", "Quarta · dispositivos, locais, programação; criativos.", "Quinta · públicos.", "Grupos: View Video, inscritos, envolvimento, interesses, ≥15 palavras-chave, ≥50 canais."],
    d1: [["Abertura", "Fratura emocional: 'Eu amo a minha família, mas a rotina não se parece com a família que eu sonhei construir.' Regra: ninguém sai culpada."], ["Bloco 1", "RECONHECER — as cenas: tablet, ordem repetida, culpa, casal desalinhado, apagar incêndio. Exercício guiado do cenário da própria casa."], ["Bloco 2", "ENTENDER — casa no modo sobrevivência × família com direção. Nem tudo é fase; amor e limite não são opostos; autoridade não é grito."], ["Bloco 3", "DESCOBRIR — os três fundamentos na linguagem da casa, só depois nomeados: organização, autoridade, emocional."], ["Fechamento", "Tarefa: escolher UMA decisão pequena de hoje. Gancho para o Dia 2."]],
    d2: [["Abertura", "Retomar as decisões do chat. Prova: histórias reais de alunas."], ["Bloco 1", "APLICAR — demonstração em 3 situações (birra 2–4, desobediência 5–10, casal discordando)."], ["Bloco 2", "MÉTODO — transformação consistente exige método e continuidade. Desmontar as 7 objeções antes do preço."], ["Oferta", "Família Forte 2.0 como consequência lógica. Vitalício, BF antecipada, bônus de quem decide ao vivo. Checkout liberado na hora."], ["Encerramento", "Perguntas ao vivo, garantia. WhatsApp 'Oferta aberta' sai com a Paula no ar."]],
    ingressos: [["Lote 1 · R$ 27,90 · 05/10 → 31/10", "Atravessa os Atos 1, 2 e parte do 3. Bônus de entrada: gravação + material do Dia 1."], ["Lote 2 · a definir · 01/11 → 05/11", "NÃO vira antes de 01/11. Aviso em 29/10 (faltam 3 dias) + 'último dia' em 31/10."], ["Lote 3 · a definir · 06/11 e 07/11 apenas", "Aviso em 03/11 (faltam 3 dias) + 'último dia do Lote 2' em 05/11. Último lote: 'só hoje e amanhã'."], ["Vendas encerram 07/11 à meia-noite (durante o Dia 1).", "Quem entra em 07/11 recebe o replay do Dia 1 e assiste o Dia 2 ao vivo."], ["Os atos NÃO mudam com os lotes.", "Ato 1 05→14/10 · Ato 2 15→25/10 · Ato 3 26/10→06/11: os atos preparam a cabeça; os lotes criam urgência só na reta final."]],
    ofertaFF: [["Abre ao vivo no Dia 2 (08/11) · fecha 12/11 (proposta)", ""], ["Condição: acesso vitalício, Black Friday antecipada", ""], ["Não é 'biblioteca de aulas': é a metodologia que organiza o que ela percebeu.", "Filhos que aprendem limites, rotina organizada, virtudes, cuidado emocional, casal alinhado."], ["Papéis no ar: apresentação (Paula), chat, WhatsApp 1:1, ManyChat, checkout, stories", ""]],
    tensao: ["Casa no modo sobrevivência × Família com direção", "A mãe não é negligente: ama profundamente e conduz a casa sem caminho claro. O inimigo é a falta de direção, o excesso de informação desconectada e as soluções pontuais."],
    conclusoes: [["“Isso acontece na minha casa.”", "reconhecimento (Ato 1)"], ["“Talvez eu esteja tentando resolver do jeito errado.”", "quebra de crença (Ato 2)"], ["“Existe um caminho mais claro e possível.”", "esperança concreta (Ato 3)"], ["“Eu preciso aprender a conduzir isso agora.”", "decisão (Imersão)"]],
    linguagem: [["Organização", "“Uma casa que funciona.”"], ["Autoridade", "“Uma mãe que sabe conduzir sem viver gritando ou repetindo.”"], ["Emocional", "“Uma criança que aprende a lidar com o que sente.”"]],
    frases: ["Uma família forte não acontece por acaso. Ela é construída nas pequenas decisões de todos os dias.", "Seu filho não precisa de uma mãe que saiba tudo. Precisa de uma mãe que saiba conduzir.", "Talvez você não precise tentar mais. Talvez precise finalmente saber o que fazer, em que ordem e por quê.", "Você não precisa resolver cada problema da sua casa separadamente.", "Não é sobre ser uma mãe perfeita. É sobre ter direção.", "A mudança da sua família começa dentro de casa — e começa nas decisões de hoje."],
    obj: [["“Já tentei de tudo.”", "Não faltou tentativa; faltou visão integrada e sequência de aplicação."], ["“Já fiz outros cursos.”", "Consumir informação e transformar a rotina são coisas diferentes."], ["“É só uma fase.”", "Distinguir desenvolvimento esperado de padrões que pedem direção — sem alarmismo."], ["“Meu marido acha frescura.”", "Conteúdo que inclui o casal e mostra o custo do desalinhamento."], ["“Com meu filho não funciona.”", "Casos diversos, princípios adaptáveis, sem promessa universal."], ["“Não tenho tempo.”", "O método cabe na rotina real."], ["“Não quero me sentir mais culpada.”", "A campanha não acusa: troca culpa por clareza."]],
    nao: ["Não transformar a criança em vilã.", "Não construir a campanha sobre medo extremo do futuro dos filhos.", "Não prometer filho perfeito, obediência absoluta ou ausência de conflitos.", "Não culpabilizar a mãe para vender.", "Não abrir com termos técnicos de psicologia.", "Não entregar dicas aleatórias sem conexão com a história maior.", "Não deixar cada canal parecer uma campanha diferente.", "Não depender de desconto para criar desejo.", "Não mudar a base de conteúdo da Paula: o que muda é a CTA, não o conteúdo.", "Não virar lote antes da data: Lote 2 só em 01/11, Lote 3 só em 06/11."],
    canais: [["Instagram (posts — mesma base)", "identificação e descoberta · toda legenda com CTA da palavra-chave"], ["Lives", "aprofundam consciência e chamam para o evento"], ["ManyChat", "transforma comentário/DM em link do ingresso"], ["Páginas A (sem VSL) e B (com VSL)", "convertem em compra · mesmo checkout"], ["E-mail", "desenvolve o raciocínio"], ["WhatsApp (API)", "aproxima, lembra e conduz quem comprou"], ["Provas sociais", "demonstram possibilidade"], ["Imersão", "organiza tudo"], ["Família Forte 2.0", "implementação e continuidade"]]
  };
  return { CONTENT_V, tasks, content };
})();
